name: Tests

on: [push,pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.0'
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3.3.1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Execute tests
        run: php artisan test
